name: Deploy pages
on: push
permissions:
  id-token: write
  contents: read
  pull-requests: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: cd dry-rb && npm install
      - name: Build
        run: cd dry-rb && npm run build
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dry-rb/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}